### ISSUE TITLE
Authenticate cookie stop working 4 or 5 days after login

### ISSUE THREAD

**Issue by Lightup1** [moritzgloeckl/overleaf-sync#55]
After login a cookie is stored. And it works fine.
But for 4 or 5 days later, I can not query my project by that cookie and I need to re-run `ols login` to generate a new cookie file.
Is this a bug from `ols` or just an expiration of overleaf cookie set by overleaf server?

**Comment by moritzgloeckl** [comment]
Probably the cookie is only valid for 4 or 5 days, might need to check that. Possibly we should implement a cookie reload functionality as well.

**Comment by moritzgloeckl** [comment]
It seems it updates the cookie if you do anything within exactly 5 days. If you do not query or sync your project your cookie expires. I guess the site also logs you out after 5 days of inactivity.

Could you please try not doing anything for 5 days on overleaf.com and confirm you're logged out after that?

If that is the case I guess we cannot do anything against that. It's a security measurement taken by overleaf.com and they can set-up how long they think their cookie is valid...

**Comment by Lightup1** [comment]
@moritzgloeckl , it seems true that overleaf.com will confirm me as logged out after several days of doing nothing.
Is it possible to make ols automatically do some virtual login action without changing anything in the project but just make the cookie to be valid?
Like openning a software in the background which will connect to overleaf.com with the cookie to make the cookie valid.

**Comment by moritzgloeckl** [comment]
It could work if you just call `ols list` periodically, it should then "refresh" the cookie on overleaf's side. Virtual login action would not be working because I don't want to store the user's password and furthermore, their login is protected by CAPTCHA, so that wouldn't work either.

I'd suggest you use your OS's best tool (CRON on Linux for example) to periodically call `ols list` and you shouldn't be logged out then.
